### ISSUE TITLE
Remove Changelog.md from shipped framework

### ISSUE THREAD

**Issue by empowerRyanFerrell** [persona-id/inquiry-ios#1]
Smallest of issues...

We noticed, while peeping at our app's install footprint for opportunities to slim down, that a little speck of your framework's 7.9 MB stripped size is the developer-facing `Changelog.md`. Mind removing that?

If other small wins might be on the table, unzipping PhoneNumberMetadata.json when needed could save ~310 kb.

<img width="2266" alt="Screenshot 2023-08-24 at 1 34 19 AM" src="https://github.com/persona-id/inquiry-ios/assets/128399819/fd9c4afe-21a4-44aa-b29e-19c095fc9ea2">

**Comment by jacoblange-dev** [comment]
sure, I've made the change to remove the changelog from our target. I believe we can remove phonenumbermetadata.json as well but requires a little effort, filed an issue internally to take a look sometime soon.

**Comment by jacoblange-dev** [comment]
turns out removing `PhoneNumberMetadata.json` was easier than I thought so I've done that as well, will cut a release (v2.12.1) later today with these two changes.

**Comment by empowerRyanFerrell** [comment]
Thanks! Will you be able to cut a release soon?
